name: Delete Markdown Files

on:
  workflow_dispatch:
    inputs:
      manualrun:
        description: 'Manually run workflow'
        required: true

jobs:
  delete_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Delete Markdown files
        run: |
          rm -f src/routes/texts/*.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Delete Markdown files" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
